<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xccn9A\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xccn9A/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5xccn9A.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5xccn9A\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5xccn9A\App_KernelDevDebugContainer([
    'container.build_hash' => '5xccn9A',
    'container.build_id' => '11936640',
    'container.build_time' => 1733512288,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xccn9A');
